# Generated by Django 3.2.7 on 2021-10-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpage',
            old_name='subpage_url',
            new_name='subpage_anchor',
        ),
        migrations.AddField(
            model_name='page',
            name='page_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
