# Generated by Django 3.2.7 on 2021-10-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20211001_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='filmbts')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.gallery')),
            ],
        ),
    ]
