# Generated by Django 3.2.7 on 2021-10-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_gallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='alt',
            new_name='name',
        ),
    ]
