# Generated by Django 3.2.7 on 2021-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_rename_alt_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterModelTable(
            name='image',
            table='filmbts',
        ),
    ]
