# Generated by Django 3.2.7 on 2021-10-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20211015_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desc',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
