# Generated by Django 3.2.7 on 2021-10-31 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='credit',
            name='person_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.creditarea'),
        ),
    ]
